title: "Yash Jain"
description: "Personal academic website of Yash Jain"
baseurl: ""
url: "https://yashj1579.github.io"

# Hide the RSS/Atom feed link in footer and head
atom_feed:
  hide: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: null    # tells Jekyll: don't use theme's home layout

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-coffeescript
  - jekyll-include-cache

collections:
  pages:
    output: true

