title: "Yash Jain"
description: "PhD student in Computer and Information Science at the University of Pennsylvania. Research in control, game theory, and autonomous systems."
baseurl: ""
url: "https://yashj1579.github.io"

# Hide the RSS/Atom feed link in footer and head
atom_feed:
  hide: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: null    # tells Jekyll: don't use theme's home layout
  - scope:
      path: ""
      type: "posts"
    values:
      layout: blog-post
  - scope:
      path: "google.html"
    values:
      sitemap: false
  - scope:
      path: "googlefd165c729e6d196a.html"
    values:
      sitemap: false
  - scope:
      path: "yash-newtab-extension"
    values:
      sitemap: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-coffeescript
  - jekyll-include-cache

collections:
  pages:
    output: true

